language: go
go:
        - 1.7.x
        - 1.8.x
        - 1.x
        - tip

before_install:
        - go get github.com/mattn/goveralls

script:
        - go test -v -race ./...
        - $HOME/gopath/bin/goveralls -service=travis-ci -v
